### 100 Python Coding Challenges

In [1]:
# Importing all the libraries
import math
import numpy as np

### Question 1 Level 1

Question:
Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5,
between 2000 and 3200 (both included).
The numbers obtained should be printed in a comma-separated sequence on a single line.

Hints: 
Consider use range(#begin, #end) method

In [1]:
l1 = [str(x) for x in range(2000,3200) if (x%7 == 0 and x%5 != 0) ]

print(','.join(l1))

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199


### Question 2 Level 1

Question:
Write a program which can compute the factorial of a given numbers.
The results should be printed in a comma-separated sequence on a single line.
Suppose the following input is supplied to the program:
8
Then, the output should be:
40320

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.x

In [2]:
# Methon 1
def get_fact(num):
    if num == 0:
        return 1
    fact = 1
    for x in range(1,num+1):   ## as in range function boundary values are not included
        fact = fact * x
    return fact
get_fact(8)

40320

In [3]:
# Method 2 

def get_fact_recursion(num):
    if num == 0:
        return 1
    return num*get_fact_recursion(num-1)
get_fact_recursion(8)

40320

### Question 3 Level 1

Question:
With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary.
Suppose the following input is supplied to the program:
8
Then, the output should be:
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.
Consider use dict()

In [4]:
def squre_dict(num):
    return {x : x**2 for x in range(1,num+1)}
squre_dict(10)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

### Question 4 Level 1

Question:
Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.
Suppose the following input is supplied to the program:
34,67,55,33,12,98
Then, the output should be:
['34', '67', '55', '33', '12', '98']
('34', '67', '55', '33', '12', '98')

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.
tuple() method can convert list to tuple


In [5]:
def list_tuple_conversion(input):
    values = input.split(',')
    print(tuple(values))
    print(list(values))
list_tuple_conversion('1,2,4,4')

('1', '2', '4', '4')
['1', '2', '4', '4']


### Question 5 Level 1

Question:
Define a class which has at least two methods:
getString: to get a string from console input
printString: to print the string in upper case.
Also please include simple test function to test the class methods.

Hints:
Use __init__ method to construct some parameters

In [11]:
class InputOutString():
    def __init__(self):
        self.s = 'default'
    
    def get_string(self):
        self.s = input('Please provide some string values :')
        
    def print_string(self):
        print(self.s.upper())

inputOutString = InputOutString()
print('Before getting string :', inputOutString.s)
inputOutString.get_string()
print('After getting string :', inputOutString.s) 

Before getting string : default
Please provide some string values :new val
After getting string : new val


### Question 6 Level 2

Question:
Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H:
C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated sequence.
Example
Let us assume the following comma separated input sequence is given to the program:
100,150,180
The output of the program should be:
18,22,24

Hints:
If the output received is in decimal form, it should be rounded off to its nearest value (for example, if the output received is 26.0, it should be printed as 26)
In case of input data being supplied to the question, it should be assumed to be a console input. 

In [37]:
input_vals = input('Please provide the values of D e.g.  100,150,180 ')
C, H = 50 , 30
D = [int(x) for x in input_vals.split(',')]
Q = [str(round(math.sqrt((2 * C * x)/H), 2)) for x in D]
print('Q : ', ','.join(Q))

Please provide the values of D e.g.  100,150,180  100,150,180
Q :  18.26,22.36,24.49


### Question 7 Level 2

Question:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,¡­Y-1.
Example
Suppose the following inputs are given to the program:
3,5
Then, the output of the program should be:
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]] 

In [32]:
input_vals = input('Please provide the inputs.  ')
X,Y = [int(x) for x in input_vals.split(',')]

ij_mat = []
for x in range(X):
    for y in range(Y):
        ij_mat.append(x*y)

ij_array = np.array(ij_mat).reshape(X, Y)
print(ij_array)

Please provide the inputs.  4,4
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]


### Question 8 Level 2

Question:
Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.
Suppose the following input is supplied to the program:
without,hello,bag,world
Then, the output should be:
bag,hello,without,world

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.

In [36]:
input_vals = input('Please provide the inputs values e.g without,hello,bag,world  :')
string_vals = input_vals.split(',')
sorted_string = sorted(string_vals)
print(','.join(sorted_string))

Please provide the inputs values e.g without,hello,bag,world  :without,hello,bag,world
bag,hello,without,world


### Question 9 Level 2

Question£º
Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.
Suppose the following input is supplied to the program:
Hello world
Practice makes perfect
Then, the output should be:
HELLO WORLD
PRACTICE MAKES PERFECT

In [39]:
input_vals = input('Please provide the inputs values e.g  Hello world Practice makes perfect  :')
##string_vals = [x.upper for x in input_vals.split(' ')]
##print(' '.join(string_vals))

input_vals.upper()

Please provide the inputs values e.g  Hello world Practice makes perfect  :Hello world Practice makes perfect


'HELLO WORLD PRACTICE MAKES PERFECT'

### Question 10 Level 2

Question:
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.
Suppose the following input is supplied to the program:
hello world and practice makes perfect and hello world again
Then, the output should be:
again and hello makes perfect practice world

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.
We use set container to remove duplicated data automatically and then use sorted() to sort the data.

In [41]:
input_vals = input('Please provide the inputs values e.g hello world and practice makes perfect and hello world again  :')
non_duplicate_strings = set(input_vals.split(' '))
print(' '.join(sorted(non_duplicate_strings)))

Please provide the inputs values e.g hello world and practice makes perfect and hello world again  :hello world and practice makes perfect and hello world again
again and hello makes perfect practice world


### Question 11 Level 2

Question:
Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.
Example:
0100,0011,1010,1001
Then the output should be:
1010
Notes: Assume the data is input by console.

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.


In [51]:
input_vals = input('Please provide the inputs values e.g 0100,0011,1010,1001  :')
list_five_divisible = [str(int(x,base =2)) for x in input_vals.split(',') if int(x,base =2) % 5 ==0]
print(','.join(list_five_divisible))

Please provide the inputs values e.g 0100,0011,1010,1001  :0100,0011,1010,1001
10


### Question 12 Level 2

Question:
Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number.
The numbers obtained should be printed in a comma-separated sequence on a single line.

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.

In [63]:
min = 1000
max = 3000
list_int = [str(x) for x in  range(min, max+1) if (int(str(x)[0])%2 == 0 and  int(str(x)[1])%2 == 0 and  int(str(x)[2])%2 == 0 and int(str(x)[3])%2 == 0)]
print(', '.join(list_int))

2000, 2002, 2004, 2006, 2008, 2020, 2022, 2024, 2026, 2028, 2040, 2042, 2044, 2046, 2048, 2060, 2062, 2064, 2066, 2068, 2080, 2082, 2084, 2086, 2088, 2200, 2202, 2204, 2206, 2208, 2220, 2222, 2224, 2226, 2228, 2240, 2242, 2244, 2246, 2248, 2260, 2262, 2264, 2266, 2268, 2280, 2282, 2284, 2286, 2288, 2400, 2402, 2404, 2406, 2408, 2420, 2422, 2424, 2426, 2428, 2440, 2442, 2444, 2446, 2448, 2460, 2462, 2464, 2466, 2468, 2480, 2482, 2484, 2486, 2488, 2600, 2602, 2604, 2606, 2608, 2620, 2622, 2624, 2626, 2628, 2640, 2642, 2644, 2646, 2648, 2660, 2662, 2664, 2666, 2668, 2680, 2682, 2684, 2686, 2688, 2800, 2802, 2804, 2806, 2808, 2820, 2822, 2824, 2826, 2828, 2840, 2842, 2844, 2846, 2848, 2860, 2862, 2864, 2866, 2868, 2880, 2882, 2884, 2886, 2888


### Question 13 Level 2

Question:
Write a program that accepts a sentence and calculate the number of letters and digits.
Suppose the following input is supplied to the program:
hello world! 123
Then, the output should be:
LETTERS 10
DIGITS 3

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.


In [70]:
input_vals = input('Please provide the inputs values e.g hello world! 123  :')
counter = {'LETTERS':0 , 'DIGITS': 0}
for x in input_vals:
    if(x.isdigit()):
        counter['DIGITS'] += 1
    elif(x.isalpha()):
        counter['LETTERS'] += 1
    else:
        pass
##print('LETTERS: {counter['LETTERS']}, DIGITS : {counter['DIGITS']}' )
counter

Please provide the inputs values e.g hello world! 123  :hello world! 123


{'LETTERS': 10, 'DIGITS': 3}

### Question 14 Level 2

Question:
Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters.
Suppose the following input is supplied to the program:
Hello world!
Then, the output should be:
UPPER CASE 1
LOWER CASE 9

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.

In [2]:
input_values = input('Please enter input e.g Hello world')
counter = {'UPPER CASE':0, 'LOWER CASE':0}
for x in input_values:
    if x.isupper():
        counter['UPPER CASE'] +=1
    elif x.islower():
        counter['LOWER CASE'] +=1
    else:
        pass
counter

Please enter input e.g Hello worldHello world


{'UPPER CASE': 1, 'LOWER CASE': 9}

### Question 15 Level 2

Question:
Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a.
Suppose the following input is supplied to the program:
9
Then, the output should be:
11106

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.

In [12]:
a = input('Please enter the input e.g. 9 ')
number = int(f'{a}') + int(f'{a}{a}') + int(f'{a}{a}{a}') + int(f'{a}{a}{a}{a}')
print(number)

Please enter the input e.g. 9 9
11106


### Question 16 Level 2

Question:
Use a list comprehension to square each odd number in a list. The list is input by a sequence of comma-separated numbers.
Suppose the following input is supplied to the program:
1,2,3,4,5,6,7,8,9
Then, the output should be:
1,3,5,7,9

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.

In [16]:
input_values = input('Please enter input e.g 1,2,3,4,5,6,7,8,9 : ')
odd_list = [x for x in input_values.split(',')   if int(x) % 2 ==1]
print(','.join(odd_list))

Please enter input e.g 1,2,3,4,5,6,7,8,9 : 1,8,9
1,9


### Question 17 Level 2

Question:
Write a program that computes the net amount of a bank account based a transaction log from console input. The transaction log format is shown as following:

D 100

W 200

In [19]:
input_values = input('Please provide an input : ')
total = 0
for x in input_values.split('\n'):
    if('D' in x):
        total +=int(x[2:])
    elif('W' in x):
        total -=int(x[2:])
    else:
        pass
print(total)

Please provide an input : D 100W 200 D 300


ValueError: invalid literal for int() with base 10: '100W 200 D 300'

### Question 18 Level 3

Question:
A website requires the users to input username and password to register. Write a program to check the validity of password input by users.
Following are the criteria for checking the password:
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.
Example
If the following passwords are given as input to the program:
ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be:
ABd1234@1

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.

### Question 19 Level 3

Question:
You are required to write a program to sort the (name, age, height) tuples by ascending order where name is string, age and height are numbers. The tuples are input by console. The sort criteria is:
1: Sort based on name;
2: Then sort based on age;
3: Then sort by score.
The priority is that name > age > score.
If the following tuples are given as input to the program:
Tom,19,80
John,20,90
Jony,17,91
Jony,17,93
Json,21,85
Then, the output of the program should be:
[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.
We use itemgetter to enable multiple sort keys.


### Question 20 Level 3

Question:
Define a class with a generator which can iterate the numbers, which are divisible by 7, between a given range 0 and n.

Hints:
Consider use yield

In [4]:
# using yield in 
def sever_div_gen(num):
    for i in range(1, num+1):
        if i%7 == 0:
            yield  i

for i in sever_div_gen(14):
    print(i)

7
14


### Question 21 Level 3

Question£º
A robot moves in a plane starting from the original point (0,0). The robot can move toward UP, DOWN, LEFT and RIGHT with a given steps. The trace of robot movement is shown as the following:
UP 5
DOWN 3
LEFT 3
RIGHT 2
¡­
The numbers after the direction are steps. Please write a program to compute the distance from current position after a sequence of movement and original point. If the distance is a float, then just print the nearest integer.
Example:
If the following tuples are given as input to the program:
UP 5
DOWN 3
LEFT 3
RIGHT 2
Then, the output of the program should be:
2

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.
