In [3]:
#Multiple Linear Regression

#Import the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
#Importing datasets
dataset =pd.read_csv('E:\\Machine Learning A-Z Template Folder\\Part 2 - Regression\\Section 5 - Multiple Linear Regression\\Multiple_Linear_Regression\\50_Startups.csv')
#print(dataset)

X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,4].values

#Encoding Categorical Data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder = LabelEncoder()
onehotEncoder = OneHotEncoder(categorical_features = [3])


X[:,3] =labelencoder.fit_transform(X[:,3])
X = onehotEncoder.fit_transform(X).toarray()
#print(X)

#Avoid dummy variable trap
X = X[:,1:]
print(X)


from sklearn.cross_validation import train_test_split
X_train,X_test,Y_train,Y_test =train_test_split(X,Y,test_size=0.2, random_state= 0)


[[0.0000000e+00 1.0000000e+00 1.6534920e+05 1.3689780e+05 4.7178410e+05]
 [0.0000000e+00 0.0000000e+00 1.6259770e+05 1.5137759e+05 4.4389853e+05]
 [1.0000000e+00 0.0000000e+00 1.5344151e+05 1.0114555e+05 4.0793454e+05]
 [0.0000000e+00 1.0000000e+00 1.4437241e+05 1.1867185e+05 3.8319962e+05]
 [1.0000000e+00 0.0000000e+00 1.4210734e+05 9.1391770e+04 3.6616842e+05]
 [0.0000000e+00 1.0000000e+00 1.3187690e+05 9.9814710e+04 3.6286136e+05]
 [0.0000000e+00 0.0000000e+00 1.3461546e+05 1.4719887e+05 1.2771682e+05]
 [1.0000000e+00 0.0000000e+00 1.3029813e+05 1.4553006e+05 3.2387668e+05]
 [0.0000000e+00 1.0000000e+00 1.2054252e+05 1.4871895e+05 3.1161329e+05]
 [0.0000000e+00 0.0000000e+00 1.2333488e+05 1.0867917e+05 3.0498162e+05]
 [1.0000000e+00 0.0000000e+00 1.0191308e+05 1.1059411e+05 2.2916095e+05]
 [0.0000000e+00 0.0000000e+00 1.0067196e+05 9.1790610e+04 2.4974455e+05]
 [1.0000000e+00 0.0000000e+00 9.3863750e+04 1.2732038e+05 2.4983944e+05]
 [0.0000000e+00 0.0000000e+00 9.1992390e+04 1.35495

C:\Users\adash\AppData\Local\Continuum\anaconda3\envs\practice\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:
# Fitting Multiple Lenear Regression To Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

# Predicting the Test results
y_pred = regressor.predict(X_test)

# Builing the optimal model using Backword Elemination
import statsmodels.formula.api as sm
X = np.append(arr = np.ones((50,1)).astype(int) ,values = X , axis =1)
X_opt= X[:,[0,1,2,3,4,5]]
regresior_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
print(regresior_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Thu, 18 Oct 2018   Prob (F-statistic):           1.34e-27
Time:                        16:47:36   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.0

In [8]:
X_opt= X[:,[0,1,3,4,5]]
regresior_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
print(regresior_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Thu, 18 Oct 2018   Prob (F-statistic):           8.49e-29
Time:                        16:50:42   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.0

In [11]:
X_opt= X[:,[0,4,5]]
regresior_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
print(regresior_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.610
Model:                            OLS   Adj. R-squared:                  0.593
Method:                 Least Squares   F-statistic:                     36.71
Date:                Thu, 18 Oct 2018   Prob (F-statistic):           2.50e-10
Time:                        16:54:49   Log-Likelihood:                -577.13
No. Observations:                  50   AIC:                             1160.
Df Residuals:                      47   BIC:                             1166.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.022e+04   1.77e+04      1.143      0.2